image: atlassian/default-image:2

pipelines:
  default:
    - step:
        script:
          - mkdir artifact
          - echo "Pipelines is awesome!" > artifact/index.html
        artifacts:
          - artifact/*
    - step:
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.7
            variables:
              AWS_ACCESS_KEY_ID: 'AKIAZEMZYKPMIHYCDKX3'
              AWS_SECRET_ACCESS_KEY: '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'
              AWS_DEFAULT_REGION: 'eu-central-1'
              S3_BUCKET: 'keepershomeclient'
              EXPIRES: '2021-10-01'
              LOCAL_PATH: 'artifact'
              ACL: 'public-read'